language: java
before_install:
 - git clone https://github.com/SpoonLabs/gumtree-spoon-ast-diff.git
 - cd gumtree-spoon-ast-diff
 - mvn install -Dmaven.test.skip=true -DskipTests=true
 - cd ..
 - git clone https://github.com/tdurieux/patch-clustering.git
 - cd patch-clustering
 - mvn install -Dmaven.test.skip=true -DskipTests=true
 - cd ..
script:
 - java -jar patch-clustering/target/patchclustering-0.1-SNAPSHOT-jar-with-dependencies.jar --bugId chart_1 --buggySourceDirectory ./benchmark/defects4j/chart_1/buggy-version --fixedSourceDirectory ./benchmark/defects4j/chart_1/buggy-version --diff ./benchmark/defects4j/chart_1/path.diff -m ALL
